name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update and bump
        run: |
          curl -Lo system/etc/hosts https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          sed -i "3s/.*/version=$(date '+%Y-%m-%d')/" module.prop
          sed -i "4s/.*/versionCode=$(date '+%y%m%d')/" module.prop

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Auto Update"
